// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateUserInput struct {
	Email    string `json:"email"`
	FullName string `json:"fullName"`
	Password string `json:"password"`
}

type GetUserInput struct {
	ID int `json:"id"`
}

type Mutation struct {
}

type Query struct {
}

type User struct {
	ID               int      `json:"id"`
	Username         string   `json:"username"`
	Email            string   `json:"email"`
	FullName         string   `json:"fullName"`
	Avatar           *string  `json:"avatar,omitempty"`
	Interests        []int    `json:"interests"`
	Communities      []int    `json:"communities,omitempty"`
	Posts            []int    `json:"posts,omitempty"`
	Rating           *int     `json:"rating,omitempty"`
	Level            *int     `json:"level,omitempty"`
	AboutMe          *string  `json:"aboutMe,omitempty"`
	Links            []string `json:"links,omitempty"`
	PublicProfileURL *string  `json:"publicProfileURL,omitempty"`
}
